name: Run Tests

on:
  push:
      branches: main
  pull_request:
      branches: main

jobs:
    build:
          runs-on: ubuntu-latest

          steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 22
            - run: npm ci
            - name: Set environment variables
              run: echo "DB_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
            - run: npm test
            - name: Check DB_URL
              run: echo "DB_URL is $DB_URL"
